# EnigmaIRC Server port
# DO NOT USE YOUR SERVER PORT
port: 6667

# What messages from EIRC will look like in the game
# Supports Kyori's components (read more at https://docs.advntr.dev/text.html)
chat-format: "[EIRC] <user> - <message>"

# Client encryption key
encryption-key: ""